# Generated by Django 3.0.8 on 2020-07-09 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11)),
                ('birthdate', models.DateField()),
                ('amount_wanted', models.DecimalField(decimal_places=2, max_digits=6)),
                ('terms_wanted', models.IntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('status', (('CP', 'Completed'), ('PS', 'Processing'))), ('result', (('AP', 'Approved'), ('RF', 'Refused'))), ('refused', (('AG', 'Age'), ('SC', 'Score'), ('CM', 'Commitment'))), ('unknown', 'Unknown')], default='PS', max_length=10)),
                ('result', models.CharField(blank=True, choices=[('status', (('CP', 'Completed'), ('PS', 'Processing'))), ('result', (('AP', 'Approved'), ('RF', 'Refused'))), ('refused', (('AG', 'Age'), ('SC', 'Score'), ('CM', 'Commitment'))), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('refused_policy', models.CharField(blank=True, choices=[('status', (('CP', 'Completed'), ('PS', 'Processing'))), ('result', (('AP', 'Approved'), ('RF', 'Refused'))), ('refused', (('AG', 'Age'), ('SC', 'Score'), ('CM', 'Commitment'))), ('unknown', 'Unknown')], max_length=10, null=True)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('terms_approved', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
